# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# 
development:
  adapter: mysql
  encoding: utf8
  database: signal_development
  username: root
  password: 
  host: localhost

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: silent

production:
  adapter: mysql
  encoding: utf8
  database: signal_production
  username: root
  password: 
  host: localhost

